### ISSUE TITLE
[BREAKING] none of Larry's actual passwords are included in the repo named "LarrysPasswords"

### ISSUE THREAD

**Issue by jnguyen1098** [qawse3dr/LarrysPasswordManager#1]
Misleading repo; please rename if this is intentional behaviour. Thanks.

Jason

**Comment by qawse3dr** [comment]
what do you mean my passwords are clearly here
https://github.com/qawse3dr/LarrysPasswordManager/blob/110e664c09f7a6207f640ddf8127df12abcbab95/example_secret.h#L22

**Comment by jnguyen1098** [comment]
> what do you mean my passwords are clearly here
> 
> https://github.com/qawse3dr/LarrysPasswordManager/blob/110e664c09f7a6207f640ddf8127df12abcbab95/example_secret.h#L22

LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM    LGTM
